name: Run C# Program

on:
  workflow_dispatch:  #enables to trigger 
    inputs:
      repository: 
        default: "samplerepo"
        type: string
        required: true
      flaglist:
        default: "none"
        required: false
        type: string
        description: "list of flag to procss"
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Run C# code
        run: |
          echo 'using System; class Program { static void Main() { Console.WriteLine("Hello, World!"); } }' > Program.cs
          dotnet new console -n MyApp -o MyApp
          mv Program.cs MyApp/
          cd MyApp
          dotnet run
